<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:ns="http://northgateps.com/BEIS/GetPartyDetailsRequest"
xmlns:ns1="http://northgateps.com/BEIS/GetPartyDetailsResponse"
xmlns:wsdl1="http://www.northgateps.com/GetPartyDetails.wsdl"
name="GetPartyDetails"
targetNamespace="http://www.northgateps.com/GetPartyDetails.wsdl">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://northgateps.com/BEIS/GetPartyDetailsRequest" schemaLocation="GetPartyDetailsRequest.xsd"/>
			<xsd:import namespace="http://northgateps.com/BEIS/GetPartyDetailsResponse" schemaLocation="GetPartyDetailsResponse.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="GetPartyDetailsRequest">
		<wsdl:part name="parameters" element="ns:GetPartyDetailsRequest" />
	</wsdl:message>
	<wsdl:message name="GetPartyDetailsResponse">
		<wsdl:part name="parameters" element="ns1:GetPartyDetailsResponse" />
	</wsdl:message>
	<wsdl:portType name="GetPartyDetailsWSDLPort">
		<wsdl:operation name="GetPartyDetailsWSDL">
			<wsdl:input message="wsdl1:GetPartyDetailsRequest" />
			<wsdl:output message="wsdl1:GetPartyDetailsResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetPartyDetailsWSDLBinding" type="wsdl1:GetPartyDetailsWSDLPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetPartyDetailsWSDL">
			<soap:operation
				soapAction="https://server/DATABASE/communication/GetPartyDetailsRequest" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetPartyDetailsService">
		<wsdl:port binding="wsdl1:GetPartyDetailsWSDLBinding" name="GetPartyDetailsWSDLPort">
			<soap:address location="https://server/DATABASE/communication/GetPartyDetailsRequest" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
